baseURL = "https://arunmozhi.in/"
languageCode = "en-us"
languagename = "English"
title = "Arunmozhi aka tecoholic"
theme = "LoveIt"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  dateformat = "Jan 02, 2006"
  [params.author]
    name = "Arunmozhi"
  [params.header]
    [params.header.title]
      name = "Arunmozhi"
  [params.home]
    [params.home.profile]
      avatarURL = "img/avatar.png"
      subtitle = ""
  [params.social]
    GitHub = "tecoholic"
    Stackoverflow = "8765631/arunmozhi"
    Linkedin = "tecoholic"
  [params.page]
    [params.page.home]
      [params.page.home.css]
        darkOverrides = "css/dark-overrides.css"
  [params.page.library]
    [params.page.library.css]
      darkOverrides = "css/dark-overrides.css"
      lightOverrides = "css/light-overrides.css"
  [params.list]
    dateFormat = "Jan 02, 2006"
  [params.section]
    dateFormat = "Jan 02, 2006"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Blog"
    url = "/blog/"
  [[menu.main]]
    weight = 2
    identifier = "about"
    name = "About"
    url = "/about/"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
